apiVersion: v1
kind: Service
metadata:
  name: my-microservice-nodeport
spec:
  type: NodePort
  selector:
    app: my-microservice
  ports:
    - protocol: TCP
      port: 80  # External port on which the service will be exposed
      targetPort: 8080  # Port on which the application is running in the pods
      nodePort: 30000  # Choose an available port (30000-32767) for NodePort
