global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'your-microservice'
    static_configs:
      - targets: ['your-microservice:50051']
