apiVersion: v1
kind: Service
metadata:
  name: grpc-microservice-nodeport-service
spec:
  selector:
    app: grpc-microservice
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: NodePort
